spin_manifest_version = 2

[application]
name = "web"
version = "0.1.0"
authors = ["codeitlikemiley <codeitlikemiley@gmail.com>"]
description = "A Leptos application running as a WASIp3 Component on Spin"

[[trigger.http]]
route = "/..."
component = "web"
executor = { type = "http" }

[component.web]
source = "target/wasm32-wasip2/release/web.wasm"
allowed_outbound_hosts = ["https://api.resend.com", "api.resend.com:443"]
key_value_stores = ["default"]
[component.web.build]
command = "WASI_RUNTIME=spin cargo leptos build --release && WASI_RUNTIME=spin LEPTOS_OUTPUT_NAME=web cargo build --lib --target wasm32-wasip2 --release --no-default-features --features ssr"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/pkg/..."
component = "web-pkg"

[component.web-pkg]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "target/site/pkg", destination = "/" }]
